using System.Collections.Immutable;
using System.Globalization;

namespace TraceCV.Services
{
    public interface ICountryProvider
    {
        IReadOnlyList<CountryItem> GetAllCountries();
    }

    public sealed record CountryItem(string Name, string Iso2);

    public sealed class CultureCountryProvider : ICountryProvider
    {
        private readonly Lazy<IReadOnlyList<CountryItem>> _countries;

        public CultureCountryProvider()
        {
            _countries = new Lazy<IReadOnlyList<CountryItem>>(() =>
            {
                var list = CultureInfo
                    .GetCultures(CultureTypes.SpecificCultures)
                    .Select(c =>
                    {
                        try { return new RegionInfo(c.LCID); } catch { return null; }
                    })
                    .Where(r => r != null)
                    .GroupBy(r => r!.TwoLetterISORegionName)
                    .Select(g =>
                    {
                        var r = g.First()!;
                        return new CountryItem(r.EnglishName, r.TwoLetterISORegionName);
                    })
                    .OrderBy(c => c.Name)
                    .ToList();

                return list;
            }, isThreadSafe: true);
        }

        public IReadOnlyList<CountryItem> GetAllCountries() => _countries.Value;
    }

    // Deterministic full ISO 3166-1 (alpha-2) list (common names)
    public sealed class StaticCountryProvider : ICountryProvider
    {
        private static readonly ImmutableArray<CountryItem> Countries = new[]
        {
            new CountryItem("Afghanistan","AF"),
            new CountryItem("Albania","AL"),
            new CountryItem("Algeria","DZ"),
            new CountryItem("American Samoa","AS"),
            new CountryItem("Andorra","AD"),
            new CountryItem("Angola","AO"),
            new CountryItem("Anguilla","AI"),
            new CountryItem("Antigua and Barbuda","AG"),
            new CountryItem("Argentina","AR"),
            new CountryItem("Armenia","AM"),
            new CountryItem("Aruba","AW"),
            new CountryItem("Australia","AU"),
            new CountryItem("Austria","AT"),
            new CountryItem("Azerbaijan","AZ"),
            new CountryItem("Bahamas","BS"),
            new CountryItem("Bahrain","BH"),
            new CountryItem("Bangladesh","BD"),
            new CountryItem("Barbados","BB"),
            new CountryItem("Belarus","BY"),
            new CountryItem("Belgium","BE"),
            new CountryItem("Belize","BZ"),
            new CountryItem("Benin","BJ"),
            new CountryItem("Bermuda","BM"),
            new CountryItem("Bhutan","BT"),
            new CountryItem("Bolivia","BO"),
            new CountryItem("Bosnia and Herzegovina","BA"),
            new CountryItem("Botswana","BW"),
            new CountryItem("Brazil","BR"),
            new CountryItem("British Virgin Islands","VG"),
            new CountryItem("Brunei","BN"),
            new CountryItem("Bulgaria","BG"),
            new CountryItem("Burkina Faso","BF"),
            new CountryItem("Burundi","BI"),
            new CountryItem("Cabo Verde","CV"),
            new CountryItem("Cambodia","KH"),
            new CountryItem("Cameroon","CM"),
            new CountryItem("Canada","CA"),
            new CountryItem("Cayman Islands","KY"),
            new CountryItem("Central African Republic","CF"),
            new CountryItem("Chad","TD"),
            new CountryItem("Chile","CL"),
            new CountryItem("China","CN"),
            new CountryItem("Colombia","CO"),
            new CountryItem("Comoros","KM"),
            new CountryItem("Congo (Republic)","CG"),
            new CountryItem("Congo (Democratic Republic)","CD"),
            new CountryItem("Cook Islands","CK"),
            new CountryItem("Costa Rica","CR"),
            new CountryItem("Côte d'Ivoire","CI"),
            new CountryItem("Croatia","HR"),
            new CountryItem("Cuba","CU"),
            new CountryItem("Curaçao","CW"),
            new CountryItem("Cyprus","CY"),
            new CountryItem("Czechia","CZ"),
            new CountryItem("Denmark","DK"),
            new CountryItem("Djibouti","DJ"),
            new CountryItem("Dominica","DM"),
            new CountryItem("Dominican Republic","DO"),
            new CountryItem("Ecuador","EC"),
            new CountryItem("Egypt","EG"),
            new CountryItem("El Salvador","SV"),
            new CountryItem("Equatorial Guinea","GQ"),
            new CountryItem("Eritrea","ER"),
            new CountryItem("Estonia","EE"),
            new CountryItem("Eswatini","SZ"),
            new CountryItem("Ethiopia","ET"),
            new CountryItem("Fiji","FJ"),
            new CountryItem("Finland","FI"),
            new CountryItem("France","FR"),
            new CountryItem("French Guiana","GF"),
            new CountryItem("French Polynesia","PF"),
            new CountryItem("Gabon","GA"),
            new CountryItem("Gambia","GM"),
            new CountryItem("Georgia","GE"),
            new CountryItem("Germany","DE"),
            new CountryItem("Ghana","GH"),
            new CountryItem("Gibraltar","GI"),
            new CountryItem("Greece","GR"),
            new CountryItem("Greenland","GL"),
            new CountryItem("Grenada","GD"),
            new CountryItem("Guadeloupe","GP"),
            new CountryItem("Guam","GU"),
            new CountryItem("Guatemala","GT"),
            new CountryItem("Guernsey","GG"),
            new CountryItem("Guinea","GN"),
            new CountryItem("Guinea-Bissau","GW"),
            new CountryItem("Guyana","GY"),
            new CountryItem("Haiti","HT"),
            new CountryItem("Honduras","HN"),
            new CountryItem("Hong Kong","HK"),
            new CountryItem("Hungary","HU"),
            new CountryItem("Iceland","IS"),
            new CountryItem("India","IN"),
            new CountryItem("Indonesia","ID"),
            new CountryItem("Iran","IR"),
            new CountryItem("Iraq","IQ"),
            new CountryItem("Ireland","IE"),
            new CountryItem("Isle of Man","IM"),
            new CountryItem("Israel","IL"),
            new CountryItem("Italy","IT"),
            new CountryItem("Jamaica","JM"),
            new CountryItem("Japan","JP"),
            new CountryItem("Jersey","JE"),
            new CountryItem("Jordan","JO"),
            new CountryItem("Kazakhstan","KZ"),
            new CountryItem("Kenya","KE"),
            new CountryItem("Kiribati","KI"),
            new CountryItem("Kuwait","KW"),
            new CountryItem("Kyrgyzstan","KG"),
            new CountryItem("Laos","LA"),
            new CountryItem("Latvia","LV"),
            new CountryItem("Lebanon","LB"),
            new CountryItem("Lesotho","LS"),
            new CountryItem("Liberia","LR"),
            new CountryItem("Libya","LY"),
            new CountryItem("Liechtenstein","LI"),
            new CountryItem("Lithuania","LT"),
            new CountryItem("Luxembourg","LU"),
            new CountryItem("Madagascar","MG"),
            new CountryItem("Malawi","MW"),
            new CountryItem("Malaysia","MY"),
            new CountryItem("Maldives","MV"),
            new CountryItem("Mali","ML"),
            new CountryItem("Malta","MT"),
            new CountryItem("Marshall Islands","MH"),
            new CountryItem("Martinique","MQ"),
            new CountryItem("Mauritania","MR"),
            new CountryItem("Mauritius","MU"),
            new CountryItem("Mayotte","YT"),
            new CountryItem("Mexico","MX"),
            new CountryItem("Micronesia","FM"),
            new CountryItem("Moldova","MD"),
            new CountryItem("Monaco","MC"),
            new CountryItem("Mongolia","MN"),
            new CountryItem("Montenegro","ME"),
            new CountryItem("Montserrat","MS"),
            new CountryItem("Morocco","MA"),
            new CountryItem("Mozambique","MZ"),
            new CountryItem("Myanmar","MM"),
            new CountryItem("Namibia","NA"),
            new CountryItem("Nauru","NR"),
            new CountryItem("Nepal","NP"),
            new CountryItem("Netherlands","NL"),
            new CountryItem("New Caledonia","NC"),
            new CountryItem("New Zealand","NZ"),
            new CountryItem("Nicaragua","NI"),
            new CountryItem("Niger","NE"),
            new CountryItem("Nigeria","NG"),
            new CountryItem("Niue","NU"),
            new CountryItem("Norfolk Island","NF"),
            new CountryItem("North Korea","KP"),
            new CountryItem("North Macedonia","MK"),
            new CountryItem("Northern Mariana Islands","MP"),
            new CountryItem("Norway","NO"),
            new CountryItem("Oman","OM"),
            new CountryItem("Pakistan","PK"),
            new CountryItem("Palau","PW"),
            new CountryItem("Palestine","PS"),
            new CountryItem("Panama","PA"),
            new CountryItem("Papua New Guinea","PG"),
            new CountryItem("Paraguay","PY"),
            new CountryItem("Peru","PE"),
            new CountryItem("Philippines","PH"),
            new CountryItem("Poland","PL"),
            new CountryItem("Portugal","PT"),
            new CountryItem("Puerto Rico","PR"),
            new CountryItem("Qatar","QA"),
            new CountryItem("Réunion","RE"),
            new CountryItem("Romania","RO"),
            new CountryItem("Russia","RU"),
            new CountryItem("Rwanda","RW"),
            new CountryItem("Saint Barthélemy","BL"),
            new CountryItem("Saint Helena","SH"),
            new CountryItem("Saint Kitts and Nevis","KN"),
            new CountryItem("Saint Lucia","LC"),
            new CountryItem("Saint Martin","MF"),
            new CountryItem("Saint Pierre and Miquelon","PM"),
            new CountryItem("Saint Vincent and the Grenadines","VC"),
            new CountryItem("Samoa","WS"),
            new CountryItem("San Marino","SM"),
            new CountryItem("São Tomé and Príncipe","ST"),
            new CountryItem("Saudi Arabia","SA"),
            new CountryItem("Senegal","SN"),
            new CountryItem("Serbia","RS"),
            new CountryItem("Seychelles","SC"),
            new CountryItem("Sierra Leone","SL"),
            new CountryItem("Singapore","SG"),
            new CountryItem("Sint Maarten","SX"),
            new CountryItem("Slovakia","SK"),
            new CountryItem("Slovenia","SI"),
            new CountryItem("Solomon Islands","SB"),
            new CountryItem("Somalia","SO"),
            new CountryItem("South Africa","ZA"),
            new CountryItem("South Korea","KR"),
            new CountryItem("South Sudan","SS"),
            new CountryItem("Spain","ES"),
            new CountryItem("Sri Lanka","LK"),
            new CountryItem("Sudan","SD"),
            new CountryItem("Suriname","SR"),
            new CountryItem("Sweden","SE"),
            new CountryItem("Switzerland","CH"),
            new CountryItem("Syrian Arab Republic","SY"),
            new CountryItem("Taiwan","TW"),
            new CountryItem("Tajikistan","TJ"),
            new CountryItem("Tanzania","TZ"),
            new CountryItem("Thailand","TH"),
            new CountryItem("Timor-Leste","TL"),
            new CountryItem("Togo","TG"),
            new CountryItem("Tokelau","TK"),
            new CountryItem("Tonga","TO"),
            new CountryItem("Trinidad and Tobago","TT"),
            new CountryItem("Tunisia","TN"),
            new CountryItem("Türkiye","TR"),
            new CountryItem("Turkmenistan","TM"),
            new CountryItem("Turks and Caicos Islands","TC"),
            new CountryItem("Tuvalu","TV"),
            new CountryItem("Uganda","UG"),
            new CountryItem("Ukraine","UA"),
            new CountryItem("United Arab Emirates","AE"),
            new CountryItem("United Kingdom","GB"),
            new CountryItem("United States","US"),
            new CountryItem("Uruguay","UY"),
            new CountryItem("Uzbekistan","UZ"),
            new CountryItem("Vanuatu","VU"),
            new CountryItem("Venezuela","VE"),
            new CountryItem("Vietnam","VN"),
            new CountryItem("Virgin Islands (U.S.)","VI"),
            new CountryItem("Wallis and Futuna","WF"),
            new CountryItem("Western Sahara","EH"),
            new CountryItem("Yemen","YE"),
            new CountryItem("Zambia","ZM"),
            new CountryItem("Zimbabwe","ZW"),
        }.ToImmutableArray();

        public IReadOnlyList<CountryItem> GetAllCountries() => Countries;
    }
}